controller_server:
    ros__parameters:
        enable_stamped_cmd_vel: true
        controller_frequency: 20.0
        odom_topic: odometry/filtered
        costmap_update_timeout: 0.5

        min_x_velocity_threshold: 0.01
        min_y_velocity_threshold: 0.01
        min_theta_velocity_threshold: 0.05
        failure_tolerance: 0.4
        use_realtime_priority: false

        progress_checker_plugin: progress_checker
        progress_checker:
            plugin: nav2_controller::SimpleProgressChecker
            movement_time_allowance: 10.0
            required_movement_radius: 0.5

        goal_checker_plugins: [goal_checker]
        goal_checker:
            plugin: nav2_controller::SimpleGoalChecker
            stateful: true
            xy_goal_tolerance: 0.1
            yaw_goal_tolerance: 0.15

        controller_plugins: [FollowPath]
        FollowPath:
            plugin: nav2_mppi_controller::MPPIController
            motion_model: DiffDrive

            time_steps: 56
            model_dt: 0.05
            batch_size: 2000

            vx_std: 0.2
            wz_std: 0.4

            vx_max: 0.62
            vx_min: -0.62
            wz_max: 5.0
            wz_min: -5.0

            iteration_count: 1
            prune_distance: 2.5
            transform_tolerance: 0.1
            temperature: 0.3
            gamma: 0.015
            regenerate_noises: true
            visualize: false
            
            critics: [
                ConstraintCritic, 
                CostCritic, 
                GoalCritic, 
                GoalAngleCritic, 
                PathAlignCritic, 
                PathFollowCritic, 
                PathAngleCritic, 
                PreferForwardCritic
            ]
            
            ConstraintCritic:
                enabled: false
                cost_power: 1
                cost_weight: 4.0
            GoalCritic:
                enabled: true
                cost_power: 1
                cost_weight: 5.0
                threshold_to_consider: 3.2
            GoalAngleCritic:
                enabled: true
                cost_power: 1
                cost_weight: 3.0
                threshold_to_consider: 0.1
            PreferForwardCritic:
                enabled: true
                cost_power: 1
                cost_weight: 7.0
                threshold_to_consider: 1.5
            CostCritic:
                enabled: true
                cost_power: 1
                cost_weight: 3.81
                critical_cost: 300.0
                consider_footprint: true
                collision_cost: 1000000.0
                near_goal_distance: 1.0
            PathAlignCritic:
                enabled: true
                cost_power: 1
                cost_weight: 14.0
                max_path_occupancy_ratio: 0.05
                trajectory_point_step: 4
                threshold_to_consider: 0.5
                offset_from_furthest: 20
                use_path_orientations: false
            PathFollowCritic:
                enabled: true
                cost_power: 1
                cost_weight: 5.0
                offset_from_furthest: 5
                threshold_to_consider: 3.2
            PathAngleCritic:
                enabled: true
                cost_power: 1
                cost_weight: 2.0
                offset_from_furthest: 4
                threshold_to_consider: 0.5
                max_angle_to_furthest: 1.0
                mode: 0

local_costmap:
    local_costmap:
        ros__parameters:
            global_frame: odom
            robot_base_frame: base_link
            transform_tolerance: 0.2
            
            update_frequency: 10.0
            publish_frequency: 5.0
            rolling_window: true
            width: 8
            height: 8
            resolution: 0.04
            always_send_full_costmap: true
            
            # 30cm x 26.5cm
            footprint: "[[-0.15, -0.1325], [0.15, -0.1325], [0.15, 0.1325], [-0.15, 0.1325]]"
            plugins: [
                obstacle_layer,
                inflation_layer
            ]
            
            inflation_layer:
                plugin: nav2_costmap_2d::InflationLayer
                cost_scaling_factor: 3.0
                inflation_radius: 0.5
            
            obstacle_layer:
                plugin: nav2_costmap_2d::ObstacleLayer
                footprint_clearing_enabled: true
                observation_sources: scan
                scan:
                    topic: <namespace>/<scan_topic>
                    clearing: true
                    marking: true
                    data_type: LaserScan
                    max_obstacle_height: 0.5
                    obstacle_max_range: 12.0
                    obstacle_min_range: 0.05
                    raytrace_max_range: 12.0
                    raytrace_min_range: 0.05

global_costmap:
    global_costmap:
        ros__parameters:
            global_frame: map
            robot_base_frame: base_link
            transform_tolerance: 0.2

            update_frequency: 5.0
            publish_frequency: 2.0
            resolution: 0.05
            always_send_full_costmap: true
            track_unknown_space: true

            # 30cm x 26.5cm
            footprint: "[[-0.15, -0.1325], [0.15, -0.1325], [0.15, 0.1325], [-0.15, 0.1325]]"
            plugins: [
                static_layer,
                obstacle_layer,
                inflation_layer
            ]
            
            inflation_layer:
                plugin: nav2_costmap_2d::InflationLayer
                cost_scaling_factor: 3.0
                inflation_radius: 0.25
                inflate_around_unknown: false
                inflate_unknown: false
            
            obstacle_layer:
                plugin: nav2_costmap_2d::ObstacleLayer
                footprint_clearing_enabled: true
                observation_sources: scan
                scan:
                    topic: <namespace>/<scan_topic>
                    clearing: true
                    marking: true
                    data_type: LaserScan
                    max_obstacle_height: 0.5
                    obstacle_max_range: 12.0
                    obstacle_min_range: 0.05
                    raytrace_max_range: 12.0
                    raytrace_min_range: 0.05
            
            static_layer:
                plugin: nav2_costmap_2d::StaticLayer
                map_subscribe_transient_local: true
                map_topic: <namespace>/map

planner_server:
    ros__parameters:
        expected_planner_frequency: 10.0

        planner_plugins: [
            GridBased
        ]

        GridBased:
            plugin: nav2_smac_planner::SmacPlanner2D
            tolerance: 0.5
            use_astar: false
            allow_unknown: true

bt_navigator:
    ros__parameters:
        global_frame: map
        robot_base_frame: base_link
        odom_topic: odometry/filtered
        default_nav_to_pose_bt_xml: ""
        default_nav_through_poses_bt_xml: ""

behavior_server:
    ros__parameters:
        enable_stamped_cmd_vel: true

        global_frame: map
        local_frame: odom
        robot_base_frame: base_link
        transform_tolerance: 0.1

        costmap_topic: local_costmap/costmap_raw
        footprint_topic: local_costmap/published_footprint
        cycle_frequency: 10.0

        recovery_plugins: [
            spin,
            backup,
            wait
        ]

        spin:
            plugin: nav2_behaviors::Spin
        backup:
            plugin: nav2_behaviors::BackUp
        wait:
            plugin: nav2_behaviors::Wait

        # Spin & backup
        simulate_ahead_time: 2.0

        # Spin
        max_rotational_vel: 1.0
        min_rotational_vel: 0.4
        rotational_acc_lim: 3.2

waypoint_follower:
    ros__parameters:
        enable_stamped_cmd_vel: true
        loop_rate: 20
        stop_on_failure: false
        waypoint_task_executor_plugin: wait_at_waypoint
        
        wait_at_waypoint:
            plugin: nav2_waypoint_follower::WaitAtWaypoint
            waypoint_pause_duration: 5

smoother_server:
    ros__parameters:
        smoother_plugins: [
            simple_smoother
        ]
        
        simple_smoother:
            plugin: nav2_smoother::SimpleSmoother
            tolerance: 1.0e-10
            max_its: 1000
            do_refinement: true

velocity_smoother:
    ros__parameters:
        enable_stamped_cmd_vel: true
        smoothing_frequency: 20.0
        scale_velocities: false
        feedback: OPEN_LOOP
        max_velocity: [0.6, 0.0, 1.0]
        min_velocity: [-0.6, 0.0, -1.0]
        max_accel: [1.5, 0.0, 1.5]
        max_decel: [-1.5, 0.0, -1.5]
        odom_topic: odom
        deadband_velocity: [0.0, 0.0, 0.0]
        velocity_timeout: 1.0

amcl:
    ros__parameters:
        global_frame_id: map
        odom_frame_id: odom
        base_frame_id: base_link
        scan_topic: <namespace>/<scan_topic>
        robot_model_type: nav2_amcl::DifferentialMotionModel

        tf_broadcast: true
        transform_tolerance: 1.0

        alpha1: 0.2
        alpha2: 0.2
        alpha3: 0.2
        alpha4: 0.2
        alpha5: 0.2

        do_beamskip: false
        beam_skip_distance: 0.5
        beam_skip_error_threshold: 0.9
        beam_skip_threshold: 0.3

        lambda_short: 0.1
        laser_model_type: likelihood_field
        laser_likelihood_max_dist: 2.0
        laser_max_range: 12.0
        laser_min_range: -1.0
        max_beams: 60
        max_particles: 2000
        min_particles: 500
        pf_err: 0.05
        pf_z: 0.99

        recovery_alpha_fast: 0.1
        recovery_alpha_slow: 0.001

        update_min_a: 0.1
        update_min_d: 0.15
        resample_interval: 1
        save_pose_rate: 0.5
        sigma_hit: 0.2
        z_hit: 0.5
        z_max: 0.05
        z_rand: 0.5
        z_short: 0.05

map_server:
    ros__parameters:
        yaml_filename: map.yaml
        frame_id: map