/**/ekf_node:
    ros__parameters:
        frequency: 20.0
        sensor_timeout: 0.05
        two_d_mode: true

        reset_on_time_jump: false
        predict_to_current_time: false
        print_diagnostics: false

        transform_time_offset: 0.0
        transform_timeout: 0.065

        map_frame: map
        odom_frame: odom
        base_link_frame: base_link
        world_frame: odom
        publish_tf: true
        publish_acceleration: false

        odom0: pos_data/encoder_odom
        odom0_queue_size: 1
        odom0_nodelay: true
        odom0_differential: false
        odom0_relative: true
        odom0_config: [false, false, false,  # X, Y, Z
                       false, false, false,  # Roll, Pitch, Yaw
                       true,  true,  false,  # Vel. X, Y, Z
                       false, false, true,   # Vel. Roll, Pitch, Yaw
                       false, false, false]  # Accel. X, Y, Z

        #imu0: pos_data/imu
        #imu0_queue_size: 5
        #imu0_nodelay: true
        #imu0_differential: false
        #imu0_relative: true
        #imu0_remove_gravitational_acceleration: true
        #imu0_config: [false, false, false,   # X, Y, Z
        #              false, false, false,   # Roll, Pitch, Yaw
        #              false, false, false,   # Vel. X, Y, Z
        #              false, false, false,   # Vel. Roll, Pitch, Yaw
        #              false, false, false]   # Accel. X, Y, Z

        # Temporary covariance values, to be tuned later.
        dynamic_process_noise_covariance: true
        process_noise_covariance: [0.05, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                   0.0,  0.05, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                   0.0,  0.0,  0.01, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                   0.0,  0.0,  0.0,  0.01, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                   0.0,  0.0,  0.0,  0.0,  0.01, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                   0.0,  0.0,  0.0,  0.0,  0.0,  0.1,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.2,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.2,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.05, 0.0,  0.0,  0.0,  0.0,  0.0,  0.0,
                                   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.01, 0.0,  0.0,  0.0,  0.0,  0.0,
                                   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.01, 0.0,  0.0,  0.0,  0.0,
                                   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.3,  0.0,  0.0,  0.0,
                                   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1.0,  0.0,  0.0,
                                   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  1.0,  0.0,
                                   0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.5]
