#  The ROS robot project - ROS 2 Deployment Docker Compose file
#  Copyright 2024 Samyar Sadat Akhavi
#  Written by Samyar Sadat Akhavi, 2024.
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https: www.gnu.org/licenses/>.

services:
    ros-robot-infra:
        build:
            dockerfile: Dockerfile
            context: ./
        container_name: ros-robot-infra
        hostname: ros-robot-infra
        network_mode: "host"
        env_file: .env
        restart: unless-stopped
        device_cgroup_rules:
            - "c *:* rmw"
        volumes:
            - ../:/home/nonroot/ros_ws
            - ../../pico_ws/libmicroros/src/rrp_pico_coms:/home/nonroot/ros_ws/src/rrp_pico_coms
            - /dev:/dev