/**/camera:
    ros__parameters:
        format: "RGB888"
        width: 1152
        height: 648
        orientation: 180
        sensor_mode: "2304:1296"
        jpeg_quality: 75
        FrameDurationLimits: [66667, 66667]  # 15 FPS
        frame_id: "camera_optical_link"